# Generated by Django 5.2.6 on 2025-09-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField()),
                ('theme', models.CharField(choices=[('CS&IA', 'Computer Science & IA'), ('SC', 'Social Scinece'), ('SE', 'Science and engineering'), ('ID', 'interdisciplinary')])),
                ('start_time', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField()),
                ('paper', models.FileField(upload_to='paper/')),
                ('status', models.CharField(choices=[('submited', 'submitted'), ('under review', 'under review'), ('accepted', 'accepted'), ('rejected', 'rejected')])),
                ('payed', models.BooleanField(default=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ConferenceApp.conference')),
            ],
        ),
    ]
