# Generated by Django 5.2.6 on 2025-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_rename_start_time_conference_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(),
        ),
    ]
