# Generated by Django 5.2.6 on 2025-10-15 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[a-zA-Z\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only alphabetic characters are allowed.', regex='^[a-zA-Z\\s-]+$')]),
        ),
    ]
